trigger:
  - '*'
  
variables:
  buildConfiguration: 'Release'
  releaseBranchName: 'release'

schedules:
- cron: '0 3 * * *'
  displayName: 'Deploy every day at 3 A.M.'
  branches:
    include:
    - release
  always: false 

stages:
  - template: yalm_templates/build.yml
  - template: yalm_templates/dev.yml
  - template: yalm_templates/test.yml
  - template: yalm_templates/staging.yml