stages:
- stage: 'Staging'
  displayName: 'Deploy to the staging environment'
  dependsOn: Test
  jobs:
  - template: azurewebapp_jobs.yml
    parameters:
      appName: '$(WebAppNameStaging)'
      environment: 'staging'
            
          