stages:
- stage: 'Test'
  displayName: 'Deploy to the test environment'
  dependsOn: Dev
  #condition: eq(variables['Build.Reason'], 'Schedule')
  jobs:
  - template: azurewebapp_jobs.yml
    parameters:
      appName: '$(WebAppNameTest)'
      environment: 'test'
